import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1 className="mb-4 text-4xl font-extrabold leading-none tracking-tight text-black md:text-5xl lg:text-6xl">
          The Caretaker App
        </h1>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
